version: "3.7"

services:
  searchflow:
    build: searchflow-container
    volumes:
      - ../project-website:/var/www/html
      - ./:/var/www/html/search-flow
      - ../Headstart:/var/www/html/headstart
      - ./entrypoint.php://var/www/html/entrypoint.php
    ports:
      - 127.0.0.1:8085:80
