openapi: 3.0.0
info:
  title: OKMaps Custom Services Demo API
  description: OKMaps Custom Services Demo API
  version: dev

servers:
  - url: please.change
    description: Internal server for testing

paths:
  /search:
    get:
      summary: search-flow entry point
      description: Initiate a search with given parameters
      parameters:
        - in: query
          name: service
          required: true
          description: The service to be used
          schema:
            type: string
            enum: [base, pubmed]
            default: base
        - in: query
          name: type
          required: true
          description: The HTTP request type. Must be `get` for the GET route
          schema:
            type: string
            enum:
              - get
        - in: query
          name: q
          required: true
          description: The search query, e.g. `digital education`
          schema:
            type : string
          example: digital education
          allowReserved: true
        - in: query
          name: from
          required: false
          description: optional. Earliest publication date in the format YYYY-MM-DD, e.g. `2000-01-01`. When the field is empty, the parameter falls back to the default. For BASE, the default is `1665-01-01`. For PubMed, the default is `1809-01-01`.
          schema:
            type: string
        - in: query
          name: to
          required: false
          description: optional. Latest publication date in the format YYYY-MM-DD, e.g. `2021-02-25`. When the field is empty, the parameter defaults to the current day.
          schema:
            type: string
        - in: query
          name: sorting
          required: false
          description: Sort order of search results, defaults to `most-relevant`
          schema:
            type : string
            enum: [most-relevant, most-recent]
            default: most-relevant
        - in: query
          name: document_types[]
          required: false
          description: |
            BASE only, optional. List of document type IDs, e.g. `121`, `14` or `15`. More information can be found in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 3. Document types.
            To add an additional document type, click on "Add item" below the input field. When the field is empty, the parameter defaults to `121` (Journal/newspaper article).
          schema:
            type: array
            items:
              oneOf:
                - type: string
                - type: integer
            default: [121]
          style: form
          explode: true
        - in: query
          name: article_types[]
          required: false
          description: |
            PubMed only, optional. List of article type strings, e.g. `journal article` or `clinical trial`. More information on article types can be found in the [PubMed documentation](https://pubmed.ncbi.nlm.nih.gov/help/#publication-types).
            To add an additional article type, click on "Add item" below the input field. When the field is empty, the parameter is not used and all article types will be searched.
          schema:
            type: array
            items:
              type: string
            default: []
          style: form
          explode: true
        - in: query
          name: min_descsize
          required: false
          description: BASE only, optional. Minimum abstract length in characters. Must be larger than 0. A value of 300 is recommended to increase the quality of knowledge maps. When the field is empty, it defaults to 300.
          schema:
            type: integer
            default: 300
        - in: query
          name: repo
          required: false
          description: | 
            BASE only, optional. Shorthand for a single repository that the search will be restricted to.
            The shorthand for a repository can be identified as follows:
            1. Search for the repository on [the BASE website](https://www.base-search.net/about/en/about_sources_date.php). 
            2. Once you have identified the repository you want to search in, click on the green question mark next to the name of the repository. 
            3. Look up the dccoll parameter as indicated in the screenshot, in this case `ftubbiepub`. This is the shorthand to be used here.
            <br><br>
            <img src="../BASE_coll_param.png" />
          schema:
            type: string
        - in: query
          name: coll
          required: false
          description: BASE only, optional. Denotes a collection of repositories that the search will be restricted to, e.g. `at` or `de`. Note that if a repository has been specified with the `repo` parameter, this paramter will be ignored. More information can be found in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 1. Collection-related queries.
          schema:
            type: string
        - in: query
          name: vis_type
          required: false
          description: Select between knowledge map and streamgraph visualisation types.
          schema:
            type: string
            enum: [overview, timeline]
        - in: query
          name: limit
          required: false
          description: Set the maximum number of documents to be considered for a streamgraph. This parameter only has an effect in conjunction with `vis_type=timeline` and has an upper ceiling of 1000.
          schema:
            type: integer
      responses:
        '200':    # status code
          description: Redirecting to the waiting page
