openapi: 3.0.0
info:
  title: OKMaps Custom Services Demo API
  description: OKMaps Custom Services Demo API
  version: dev

servers:
  - url: please.change
    description: Internal server for testing

paths:
  /search:
    get:
      summary: search-flow entry point
      description: Initiate a search with given parameters
      parameters:
        - in: query
          name: service
          required: true
          description: The aggregator service used for searching and retrieving the document data.
          schema:
            type: string
            enum: [base, pubmed]
            default: base
        - in: query
          name: type
          required: true
          description: The HTTP request type. Must be `get` for the GET route
          schema:
            type: string
            enum:
              - get
        - in: query
          name: q
          required: true
          description: |
            The search query, e.g. `digital education`.

            For BASE, we apply the verbatim search mode to improve visualization quality. Operators such as `open and science`, exclusion such as `science -research` and phrase search such as `"digital education"` is possible.

            For PubMed, the query is relayed as-is, which means advanced PubMed syntax can be applied.
          schema:
            type : string
          example: digital education
          allowReserved: true
        - in: query
          name: from
          required: false
          description: |
            Start date for the search in the format YYYY-MM-DD. When the field is left empty, the parameter falls back to the default.
            
            For BASE, the default is `1665-01-01`. This date only applies to journal articles, other data types may have earlier publication dates.
            
            For PubMed, the default is `1809-01-01`.
          schema:
            type: string
            format: date
            example: "1665-01-01"
        - in: query
          name: to
          required: false
          description: End date for the search in the format YYYY-MM-DD. When the field is left empty, the parameter defaults to the current day.
          schema:
            type: string
            format: date
            example: "2022-01-01"
        - in: query
          name: sorting
          required: false
          description: | 
            Sorting here means the way the documents are prioritized by the aggregator before the visualization is created. Defaults to `most-relevant`.

            Most relevant ranks documents according to their relevancy towards the search query, with highest relevancy first.

            Most recent ranks documents according to their recency, with most recent first.
          schema:
            type : string
            enum: [most-relevant, most-recent]
            default: most-relevant
        - in: query
          name: document_types[]
          required: false
          description: |
            BASE only. List of document type codes that the search will be restricted to, e.g. `121`, `14` or `15`. Most up-to-date information can be found in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 3. Document types.
            
            To add an additional document type, click on "Add item" below the input field. When the field is empty, the parameter defaults to `121` (Journal/newspaper article).
          schema:
            type: array
            items:
              oneOf:
                - type: string
                - type: integer
            default: [121]
          style: form
          explode: true
        - in: query
          name: article_types[]
          required: false
          description: |
            PubMed only. List of article type strings that the search will be restricted to, e.g. `journal article` or `clinical trial`. More information on article types can be found in the [PubMed documentation](https://pubmed.ncbi.nlm.nih.gov/help/#publication-types).
            To add an additional article type, click on "Add item" below the input field. When the field is empty, the parameter is not used and all article types will be searched.
          schema:
            type: array
            items:
              type: string
            default: []
          style: form
          explode: true
        - in: query
          name: min_descsize
          required: false
          description: BASE only. Minimum abstract length in characters. Must be larger than 0. A value of 300 is recommended to increase the quality of knowledge maps. When the field is empty, it defaults to 300.
          schema:
            type: integer
            default: 300
            example: 300
        - in: query
          name: repo
          required: false
          description: | 
            BASE only. Shorthand for a single content provider that the search will be restricted to.
            The shorthand for a content provider can be identified as follows:
            1. Search for the content provider within the list of content providers on [the BASE website](https://www.base-search.net/about/en/about_sources_date.php). 
            2. Once you have identified the content provider you want to search in, click on the question mark next to the name of the content provider. 
            3. Look up the dccoll parameter as indicated in the screenshot, in this case `ftubbiepub`. This is the shorthand to be used here.
            <br><br>
            <img src="../BASE_coll_param.png" />
          schema:
            type: string
        - in: query
          name: coll
          required: false
          description: BASE only. Denotes a collection of content providers that the search will be restricted to, e.g. `at` or `de`. Note that if a content provider has been specified with the `repo` parameter, this paramter will be ignored. More information can be found in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 1. Collection-related queries.
          schema:
            type: string
        - in: query
          name: title
          required: false
          description: BASE only. Leave it blank if there are no constraints for document titles. It is possible to use advanced query syntax as described in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 1.4 Query Syntax.
          schema:
            type: string
        - in: query
          name: abstract
          required: false
          description: BASE only. Leave it blank if there are no constraints for document abstracts. It is possible to use advanced query syntax as described in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 1.4 Query Syntax.
          schema:
            type: string
        - in: query
          name: keywords
          required: false
          description: BASE only. Leave it blank if there are no constraints for document keywords. It is possible to use advanced query syntax as described in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf), Appendix 1.4 Query Syntax.
          schema:
            type: string
      responses:
        '200':    # status code
          description: Redirecting to the waiting page
