"use strict";

const PUBMED_DOCTYPES_OPTIONS = [
  {id: 'adaptive clinical trial', label: 'Adaptive Clinical Trial',},
  {id: 'address', label: 'Address'},
  {id: 'autobiography', label: 'Autobiography'},
  {id: 'bibliography', label: 'Bibliography'},
  {id: 'biography', label: 'Biography'},
  {id: 'book illustrations', label: 'Book Illustrations'},
  {id: 'case reports', label: 'Case Reports'},
  {id: 'classical article', label: 'Classical Article'},
  {id: 'clinical conference', label: 'Clinical Conference'},
  {id: 'clinical study', label: 'Clinical Study'},
  {id: 'clinical trial', label: 'Clinical Trial'},
  {id: 'clinical trial protocol', label: 'Clinical Trial Protocol'},
  {id: 'clinical trial, phase i', label: 'Clinical Trial, Phase I'},
  {id: 'clinical trial, phase ii', label: 'Clinical Trial, Phase II'},
  {id: 'clinical trial, phase iii', label: 'Clinical Trial, Phase III'},
  {id: 'clinical trial, phase iv', label: 'Clinical Trial, Phase IV'},
  {id: 'clinical trial, veterinary', label: 'Clinical Trial, Veterinary'},
  {id: 'collected work', label: 'Collected Work'},
  {id: 'collected works', label: 'Collected Works'},
  {id: 'comment', label: 'Comment'},
  {id: 'comparative study', label: 'Comparative Study'},
  {id: 'congress', label: 'Congress'},
  {id: 'consensus development conference', label: 'Consensus Development Conference'},
  {id: 'consensus development conference, nih', label: 'Consensus Development Conference, NIH'},
  {id: 'controlled clinical trial', label: 'Controlled Clinical Trial'},
  {id: 'corrected and republished article', label: 'Corrected and Republished Article'},
  {id: 'dataset', label: 'Dataset'},
  {id: 'dictionary', label: 'Dictionary'},
  {id: 'directory', label: 'Directory'},
  {id: 'duplicate publication', label: 'Duplicate publication'},
  {id: 'editorial', label: 'Editorial'},
  {id: 'electronic supplementary materials', label: 'Electronic Supplementary Materials'},
  {id: 'english abstract', label: 'English Abstract'},
  {id: 'ephemera', label: 'Ephemera'},
  {id: 'equivalence trial', label: 'Equivalence Trial'},
  {id: 'evaluation studies', label: 'Evaluation Studies'},
  {id: 'evaluation study', label: 'Evaluation Study'},
  {id: 'expression of concern', label: 'Expression of Concern'},
  {id: 'festschrift', label: 'Festschrift'},
  {id: 'government publication', label: 'Government Publication'},
  {id: 'guideline', label: 'Guideline'},
  {id: 'historical article', label: 'Historical Article'},
  {id: 'interactive tutorial', label: 'Interactive Tutorial'},
  {id: 'interview', label: 'Interview'},
  {id: 'introductory journal article', label: 'Introductory Journal Article'},
  {id: 'journal article', label: 'Journal Article'},
  {id: 'lecture', label: 'Lecture'},
  {id: 'legal case', label: 'Legal Case'},
  {id: 'legislation', label: 'Legislation'},
  {id: 'letter', label: 'Letter'},
  {id: 'manuscript', label: 'Manuscript'},
  {id: 'meta analysis', label: 'Meta Analysis'},
  {id: 'multicenter study', label: 'Multicenter Study'},
  {id: 'news', label: 'News'},
  {id: 'newspaper article', label: 'Newspaper Article'},
  {id: 'observational study', label: 'Observational Study'},
  {id: 'observational study, veterinary', label: 'Observational Study, Veterinary'},
  {id: 'overall', label: 'Overall'},
  {id: 'patient education handout', label: 'Patient Education Handout'},
  {id: 'periodical index', label: 'Periodical Index'},
  {id: 'personal narrative', label: 'Personal Narrative'},
  {id: 'pictorial work', label: 'Pictorial Work'},
  {id: 'popular work', label: 'Popular Work'},
  {id: 'portrait', label: 'Portrait'},
  {id: 'practice guideline', label: 'Practice Guideline'},
  {id: 'pragmatic clinical trial', label: 'Pragmatic Clinical Trial'},
  {id: 'preprint', label: 'Preprint'},
  {id: 'publication components', label: 'Publication Components'},
  {id: 'publication formats', label: 'Publication Formats'},
  {id: 'publication type category', label: 'Publication Type Category'},
  {id: 'published erratum', label: 'Published Erratum'},
  {id: 'randomized controlled trial', label: 'Randomized Controlled Trial'},
  {id: 'randomized controlled trial, veterinary', label: 'Randomized Controlled Trial, Veterinary'},
  {
    id: 'research support, american recovery and reinvestment act',
    label: 'Research Support, American Recovery and Reinvestment Act'
  },
  {id: 'research support, n i h, extramural', label: 'Research Support, NIH Extramural'},
  {id: 'research support, n i h, intramural', label: 'Research Support, NIH Intramural'},
  {id: 'research support, non u s gov\'t', label: 'Research Support, U.S. Gov\'t'},
  {id: 'research support, u s gov\'t, non p h s', label: 'Research Support, U.S. Gov\'t, Non P.H.S'},
  {id: 'research support, u s gov\'t, p h s', label: 'Research Support, U.S. Gov\'t, P.H.S'},
  {id: 'research support, u s government', label: 'Research Support, U.S. Government'},
  {id: 'retracted publication', label: 'Retracted Publication'},
  {id: 'retraction of publication', label: 'Retraction of Publication'},
  {id: 'review', label: 'Review'},
  {id: 'scientific integrity review', label: 'Scientific Integrity Review'},
  {id: 'study characteristics', label: 'Study Characteristics'},
  {id: 'support of research', label: 'Support of Research'},
  {id: 'systematic review', label: 'Systematic Review'},
  {id: 'technical report', label: 'Technical Report'},
  {id: 'twin study', label: 'Twin Study'},
  {id: 'validation study', label: 'Validation Study'},
  {id: 'video audio media', label: 'Video Audio Media'},
  {id: 'webcasts', label: 'Webcasts'}
]

export default PUBMED_DOCTYPES_OPTIONS;
